### ISSUE TITLE
Support for udp

### ISSUE THREAD

**Issue by hulucc** [inlets/inlets-pro#13]

**Comment by alexellis** [comment]
Hi, this is going to be out of scope for the time being, unless there's customer interest.

Can you give some more context to your request?

Alex

**Comment by alexellis** [comment]
Hi Jack, thanks for the interest. UDP is not a supported usecase at this time, and I think that UDP over TCP may cause issues for you.

Happy to talk more if you want to send me an email. My email is listed on my GitHub profile. 

Alex
