### ISSUE TITLE
[DigitalOcean] Unable to start v0.8.0 inlets server: move 0.8.0 tag

### ISSUE THREAD

**Issue by gabemeola** [inlets/inlets-pro#19]
The inlet server never starts up while provisioning using: `inletsctl create` or `inlets-operator` using version 0.8.0.

1. `cloud-provision` downloads inlets-pro.service from gitlab artifact (https://github.com/inlets/cloud-provision/blob/master/provision/userdata.go)
2. `inlets-pro.service` is using same content from `v0.7.2`. This breaks startup because `--common-name` is changed to `--tls-san`.  See: https://github.com/inlets/inlets-pro/blob/0.8.0/artifacts/inlets-pro.service & https://raw.githubusercontent.com/inlets/inlets-pro/0.8.0/artifacts/inlets-pro.service

Possibly, `cloud-provision` could ping and wait for server to come online then surface error up through `inletsctl` and `inlets-operator` to make troubleshooting easier.

**Comment by alexellis** [comment]
Go sorry to hear that you encountered an issue.

What project were you using when you saw the error and which version did you try?

How can I reproduce it the way you did it? (Exact instructions)

**Comment by alexellis** [comment]
I am seeing the flags updated in the Git repo - from 3 days ago:

https://github.com/inlets/inlets-pro/commit/cbf80fff39dff5310b406ff0eb902dbde10dc3d8

The inletsctl release is from 4 days ago 

https://github.com/inlets/inletsctl/releases/tag/0.8.1

I'll create a new release and see if that gives you the expected result, however can you give me exact steps to reproduce the issue you're facing? And a version of the component?

Alex

**Comment by alexellis** [comment]
This should fix inletsctl for you - https://github.com/inlets/inletsctl/releases/tag/0.8.2

inlets-operator is just being validated now.

**Comment by gabemeola** [comment]
Thanks for the quick fix! For reference I was following this guide https://docs.inlets.dev/#/get-started/quickstart-caddy

**Comment by alexellis** [comment]
Thanks for letting me know, we should be all good now:

https://github.com/inlets/cloud-provision/releases/tag/0.3.0
https://github.com/inlets/inlets-pro/releases/tag/0.8.1
https://github.com/inlets/inlets-operator/releases/tag/0.12.0
https://github.com/inlets/inletsctl/releases/tag/0.8.2

Do see the latest blog post for inlets HTTPS tunnels with Let's Encrypt, it may be a little easier to follow too.

https://inlets.dev/blog/2021/02/11/secure-letsencrypt-tunnel.html
