### ISSUE TITLE
Allow control plane to use certbot generated LE certificates

### ISSUE THREAD

**Issue by avoidik** [inlets/inlets-pro#21]
Hello,

Nice project! I'm now experimenting with it on my VM, but I have LE generated certificates already. For `inlets-pro tcp server` I see there are two parameters available `--tls-key` and `--tls-cert`, but not `inlets-pro http server`. How can use my LE certificates with `inlets-pro http server`?

Regards

**Comment by alexellis** [comment]
Hi @avoidik that's on the roadmap for the HTTP mode, but we are waiting for user-demand. It is available for the TCP mode (you've correctly identified that :+1: )

However if you're using Let's Encrypt, inlets PRO can already obtain, rotate and manage the certificates. Why don't you sign up for a trial and kick the tires with this tutorial? https://inlets.dev/blog/2021/02/11/secure-letsencrypt-tunnel.html

Feel free to elaborate with more information (context) and the use-case for LE + certbot vs what now we provide built-in if you can.

Alex

**Comment by alexellis** [comment]
Can you say where you got your license from?

**Comment by avoidik** [comment]
I wasn't able to run it without the license tbh, fortunately `inlets-pro tcp server --help` doesn't require any license

**Comment by alexellis** [comment]
Yes, but you cannot connect anything to that other than inlets PRO, correct?

Why don't you apply for a free trial or buy a personal license? https://inlets.dev

**Comment by avoidik** [comment]
thank you @alexellis I'll give it a try, maybe basic `inlets` features will be sufficient for my homegrown experiments
