### ISSUE TITLE
Some clarity need on licensing

### ISSUE THREAD

**Issue by debarshibasak** [inlets/inlets-pro#30]
There was project called inlets before this that was released with MIT license. However, inlet-pro has a different license. 

How does it actually work? Can I still use inlet that was released with MIT license for free? Or is it violation of your license agreement.

**Comment by alexellis** [comment]
There is no longer an open source or free version of Inlets. You can however buy month by month through Gumroad. This seems to be the most popular option for individual developers.

inlets and inlets PRO refer to the same thing. 

Hope this helps. 

https://inlets.dev/blog/2021/07/27/monthly-subscription.html

**Comment by alexellis** [comment]
/set title: What's the license for inlets?

**Comment by alexellis** [comment]
You can find the EULA clearly listed in the repo here: https://github.com/inlets/inlets-pro/blob/master/EULA.md

Don't hesitate to email me if you need any more support.
