### ISSUE TITLE
My first ever issue is a correction typo.

### ISSUE THREAD

**Issue by sunkist4013** [inlets/inlets-pro#34]
The typo is found here:

https://docs.inlets.dev/tutorial/dual-tunnels/

![Screenshot_20220219-220727.png](https://user-images.githubusercontent.com/42178218/154857098-b119db5b-92bd-4776-a827-7cfcc5a2480b.png)

Nota. I have little experience with git forgive my inexperience.  And my disabilities make me forget a lot at times.
Really hoping this could help someone.

**Comment by alexellis** [comment]
Thanks for letting us know, I'll take a look

**Comment by alexellis** [comment]
Updated.
