### ISSUE TITLE
Deploying an inlets server fails on DigitalOcean Kubernetes cluster

### ISSUE THREAD

**Issue by welteki** [inlets/inlets-pro#38]
## Description
Trying to install a server with the inlets-pro chart fails.
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

`networking.k8s.io/v1beta1` used in the inlets charts is no longer supported in Kubernetes v1.22 according to the [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingressclass-v122)

## Current behaviour
Installation fails with
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

## Expected behaviour
Deployment succeeds

## Possible solution
Migrate the ingress template to use `networking.k8s.io/v1` instead of `networking.k8s.io/v1beta1`

## Environment
DigitalOcean kubernets cluster

Kuberetes version:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexellis** [comment]
Feel free to send a PR. This probably isn’t about DigitalOcean though is it, but K8s 1.22 itself
